### ISSUE TITLE
Add themes dark and light

### ISSUE THREAD

**Issue by nirsht** [komodorio/validkube#24]

**Comment by stevenovak123** [comment]
Does the theme need to be toggled ON/OFF ?. 
I currently have a solution where it takes the system preference and sets the Dark or light mode. 
IF the theme needs to be toggled ON and OFF , Please let me know where the button should be placed. 
Attaching the light mode picture below.
![validkubeLightMode_](https://user-images.githubusercontent.com/59828288/191289648-29990d0f-dfc7-4e88-afd6-8105ea77d990.png)

**Comment by stevenovak123** [comment]
This is how it looks on 1920*1080 (attached below). For dark mode I have not made anychanges and kept the dark mode to be the original color scheme of validkube.

![validkubeLightMode_](https://user-images.githubusercontent.com/59828288/191290264-8f00303d-9564-46b5-b3ab-b1da994e3b69.png)

**Comment by stevenovak123** [comment]
If the Above solution works. Please let me know . I will create a PR.

**Comment by vrindavan** [comment]
I think a toggle would make sense. Maybe three options: light/dark/system?

**Comment by nirsht** [comment]
@stevenovak123 toggle can be great, the pics looks fine. I wish that the toggle button will be with icons (like sun and moon) and not just `ON/OFF`.

**Comment by stevenovak123** [comment]
> @stevenovak123 toggle can be great, the pics looks fine. I wish that the toggle button will be with icons (like sun and moon) and not just `ON/OFF`.

Alright I can do that and will submit a PR for it in a few days.

**Comment by stevenovak123** [comment]
> I think a toggle would make sense. Maybe three options: light/dark/system?

I am currently picking up the preference from the browser itself and making it light or dark. So having a system prefernce would not make sense to me. Will just turn it into a toggle for Light and Dark

**Comment by nirsht** [comment]
> > I think a toggle would make sense. Maybe three options: light/dark/system?
> 
> I am currently picking up the preference from the browser itself and making it light or dark. So having a system prefernce would not make sense to me. Will just turn it into a toggle for Light and Dark

Sound good to use the browser itself. If any adjustments are needed in any component, feel free to change.
