### ISSUE TITLE
kubeval Project seems to be dead

### ISSUE THREAD

**Issue by mstoetzer** [komodorio/validkube#4]
seems that kubeval is dead:

- https://github.com/instrumenta/kubernetes-json-schema/issues/32#issuecomment-1021133568

The latest commit is from Apr 2021:
- https://github.com/instrumenta/kubeval/commit/062c99a2ad6554ca5798c07599fa6c06db975325

**Comment by itielshwartz** [comment]
Thanks!
Do you know if https://github.com/yannh/kubeconform includes all relevant checks and is in party with kubeval?

**Comment by s3than** [comment]
Kubeconform has feature parity and also updated API references

**Comment by nirsht** [comment]
This issue is resolved in this commit eaf51639cc4a5b3b4d2d3a9c0940324f508b0fa5
