### ISSUE TITLE
https://validkube.com/ CORS Issue

### ISSUE THREAD

**Issue by bio-boris** [komodorio/validkube#50]
Hi
It appears the tool hasn't been working for some time now.
For example when pressing  the clean button on the web UI it says
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gtgmn58dh9.execute-api.us-east-1.amazonaws.com/production/kubeneat. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
```

**Comment by itielshwartz** [comment]
Thanks for the feedback, I believe it's a new regression, will fix asap :)

**Comment by nirsht** [comment]
hey @bio-boris, I see this is happening only in the clean button. Is that occurred also in other endpoints ?

**Comment by bio-boris** [comment]
Validate may have had the same error I don't remember anymore

**Comment by nirsht** [comment]
Hi @bio-boris, we solved the issue, you can take a look at the solution at that commit b195bb26ed6ec42ac429e9e0ea8e87b44040576d

**Comment by bio-boris** [comment]
LGTM Thanks!
