### ISSUE TITLE
yaml textbox overflows in mobile view

### ISSUE THREAD

**Issue by Shubham7350** [komodorio/validkube#53]
**The text box should have a size fit to the screen width where the text in that box can overflow which can scroll and view. Also, the result textbox's navigation bar can be added scroll to view.**
**This can be solved with just media queries in CSS.**

The below images show the issue in mobile view.

![image](https://user-images.githubusercontent.com/90132010/221833044-69e4fc20-3564-4f16-af31-bbd49d97d8a2.png)
![image](https://user-images.githubusercontent.com/90132010/221833062-3152ca81-ac63-4e17-8bc6-83d7fc753e92.png)

**Comment by Shubham7350** [comment]
https://github.com/komodorio/validkube/pull/56
here I have made changes please go through my PR

**Comment by i9shubham** [comment]
https://github.com/komodorio/validkube/pull/56
This issue is resolved with this pr and merged.
